export const carsDatabase = [
	// ==========================================
	// KLASYKI I STARSZE AUTA (1998 - 2009)
	// ==========================================

	// 1. VOLVO S60 I GENERACJI (2000-2009)
	{
		id: 83,
		brand: 'Volvo',
		model: 'S60 I (2.4 Wolnossący)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 140,
		capacity: 2.4,
		yearFrom: 2000,
		yearTo: 2009,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 424,
		consumption: 8.9,
		maintenanceCost: 5,
		comfort: 8,
		price: 12000,
		safety: 7,
		reliability: 8,
		acceleration: 10.2,
	},
	{
		id: 84,
		brand: 'Volvo',
		model: 'S60 I (2.4 D5 pancerny)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Diesel',
		power: 163,
		capacity: 2.4,
		yearFrom: 2000,
		yearTo: 2009,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 424,
		consumption: 6.5,
		maintenanceCost: 6,
		comfort: 8,
		price: 15000,
		safety: 7,
		reliability: 9,
		acceleration: 9.5,
	},
	{
		id: 85,
		brand: 'Volvo',
		model: 'S60 I (2.5T AWD)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 210,
		capacity: 2.5,
		yearFrom: 2000,
		yearTo: 2009,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 424,
		consumption: 10.5,
		maintenanceCost: 7,
		comfort: 8,
		price: 20000,
		safety: 7,
		reliability: 7,
		acceleration: 7.4,
	},

	// 2. BMW SERIA 5 E39 (1995-2004)
	{
		id: 86,
		brand: 'BMW',
		model: 'Seria 5 E39 (520i)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 150,
		capacity: 2.0,
		yearFrom: 1995,
		yearTo: 2004,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 460,
		consumption: 9.5,
		maintenanceCost: 7,
		comfort: 8,
		price: 14000,
		safety: 5,
		reliability: 6,
		acceleration: 10.2,
	}, // Niska nota safety ze względu na wiek konstrukcji
	{
		id: 87,
		brand: 'BMW',
		model: 'Seria 5 E39 (530d Touring)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Diesel',
		power: 193,
		capacity: 3.0,
		yearFrom: 1995,
		yearTo: 2004,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 410,
		consumption: 7.8,
		maintenanceCost: 8,
		comfort: 8,
		price: 18000,
		safety: 5,
		reliability: 7,
		acceleration: 8.0,
	},
	{
		id: 88,
		brand: 'BMW',
		model: 'Seria 5 E39 (540i V8)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 286,
		capacity: 4.4,
		yearFrom: 1995,
		yearTo: 2004,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 460,
		consumption: 12.5,
		maintenanceCost: 9,
		comfort: 9,
		price: 35000,
		safety: 5,
		reliability: 6,
		acceleration: 6.2,
	},

	// 3. BMW SERIA 3 E46 (1998-2005)
	{
		id: 89,
		brand: 'BMW',
		model: 'Seria 3 E46 (320d)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Diesel',
		power: 150,
		capacity: 2.0,
		yearFrom: 1998,
		yearTo: 2005,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 440,
		consumption: 6.5,
		maintenanceCost: 7,
		comfort: 6,
		price: 11000,
		safety: 5,
		reliability: 5,
		acceleration: 8.9,
	},
	{
		id: 90,
		brand: 'BMW',
		model: 'Seria 3 E46 (328i)',
		condition: 'Używany',
		bodyType: 'Coupe',
		seats: 5,
		fuel: 'Benzyna',
		power: 193,
		capacity: 2.8,
		yearFrom: 1998,
		yearTo: 2005,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 410,
		consumption: 9.8,
		maintenanceCost: 7,
		comfort: 7,
		price: 25000,
		safety: 5,
		reliability: 6,
		acceleration: 7.0,
	}, // Drożejący klasyk

	// 4. VOLKSWAGEN PASSAT B5 FL (2000-2005)
	{
		id: 91,
		brand: 'Volkswagen',
		model: 'Passat B5 FL (1.9 TDI)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Diesel',
		power: 130,
		capacity: 1.9,
		yearFrom: 2000,
		yearTo: 2005,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 475,
		consumption: 6.0,
		maintenanceCost: 3,
		comfort: 6,
		price: 8000,
		safety: 5,
		reliability: 9,
		acceleration: 10.5,
	}, // Legenda taniego utrzymania
	{
		id: 92,
		brand: 'Volkswagen',
		model: 'Passat B5 FL (1.8T)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 150,
		capacity: 1.8,
		yearFrom: 2000,
		yearTo: 2005,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 475,
		consumption: 8.5,
		maintenanceCost: 4,
		comfort: 7,
		price: 9500,
		safety: 5,
		reliability: 7,
		acceleration: 9.2,
	},

	// 5. AUDI A4 B6 (2000-2004)
	{
		id: 93,
		brand: 'Audi',
		model: 'A4 B6 (1.9 TDI)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Diesel',
		power: 130,
		capacity: 1.9,
		yearFrom: 2000,
		yearTo: 2004,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 460,
		consumption: 6.0,
		maintenanceCost: 4,
		comfort: 7,
		price: 10500,
		safety: 6,
		reliability: 9,
		acceleration: 9.9,
	},
	{
		id: 94,
		brand: 'Audi',
		model: 'A4 B6 (1.8T Quattro)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Benzyna',
		power: 163,
		capacity: 1.8,
		yearFrom: 2000,
		yearTo: 2004,
		drive: 'AWD',
		transmission: 'Manualna',
		trunkSize: 442,
		consumption: 9.5,
		maintenanceCost: 6,
		comfort: 7,
		price: 13000,
		safety: 6,
		reliability: 7,
		acceleration: 8.7,
	},
	{
		id: 95,
		brand: 'Audi',
		model: 'A4 B6 (1.8T + LPG)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'LPG',
		power: 150,
		capacity: 1.8,
		yearFrom: 2000,
		yearTo: 2004,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 460,
		consumption: 10.5,
		maintenanceCost: 5,
		comfort: 7,
		price: 11500,
		safety: 6,
		reliability: 7,
		acceleration: 8.9,
	},

	// 6. TOYOTA COROLLA E12 (2001-2007)
	{
		id: 96,
		brand: 'Toyota',
		model: 'Corolla E12 (1.4 VVT-i)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 97,
		capacity: 1.4,
		yearFrom: 2001,
		yearTo: 2007,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 289,
		consumption: 6.7,
		maintenanceCost: 3,
		comfort: 5,
		price: 9000,
		safety: 5,
		reliability: 10,
		acceleration: 12.0,
	},
	{
		id: 97,
		brand: 'Toyota',
		model: 'Corolla E12 (2.0 D-4D)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Diesel',
		power: 110,
		capacity: 2.0,
		yearFrom: 2001,
		yearTo: 2007,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 402,
		consumption: 5.7,
		maintenanceCost: 4,
		comfort: 5,
		price: 10000,
		safety: 5,
		reliability: 8,
		acceleration: 10.9,
	},

	// ==========================================
	// RYNEK WTÓRNY (Od 2010 do 2022)
	// ==========================================

	// 1. VOLVO S60 II (2014-2017)
	{
		id: 1,
		brand: 'Volvo',
		model: 'S60 II (D3 Manual)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Diesel',
		power: 150,
		capacity: 2.0,
		yearFrom: 2014,
		yearTo: 2017,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 380,
		consumption: 4.8,
		maintenanceCost: 6,
		comfort: 8,
		price: 49000,
		safety: 10,
		reliability: 8,
		acceleration: 9.0,
	},
	{
		id: 2,
		brand: 'Volvo',
		model: 'S60 II (D4 Automat)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Diesel',
		power: 190,
		capacity: 2.0,
		yearFrom: 2014,
		yearTo: 2017,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 380,
		consumption: 5.2,
		maintenanceCost: 7,
		comfort: 8,
		price: 58000,
		safety: 10,
		reliability: 8,
		acceleration: 7.4,
	},
	{
		id: 3,
		brand: 'Volvo',
		model: 'S60 II (T5 Automat)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 245,
		capacity: 2.0,
		yearFrom: 2014,
		yearTo: 2017,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 380,
		consumption: 7.8,
		maintenanceCost: 7,
		comfort: 8,
		price: 65000,
		safety: 10,
		reliability: 7,
		acceleration: 6.3,
	},
	{
		id: 4,
		brand: 'Volvo',
		model: 'S60 II (T6 AWD)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 306,
		capacity: 2.0,
		yearFrom: 2014,
		yearTo: 2017,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 380,
		consumption: 8.9,
		maintenanceCost: 8,
		comfort: 8,
		price: 79000,
		safety: 10,
		reliability: 7,
		acceleration: 5.9,
	},

	// 2. CITROEN C4 III (Używane, 2021-2022)
	{
		id: 5,
		brand: 'Citroen',
		model: 'C4 III (1.2 PureTech 100)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 100,
		capacity: 1.2,
		yearFrom: 2021,
		yearTo: 2022,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 380,
		consumption: 5.4,
		maintenanceCost: 4,
		comfort: 8,
		price: 62000,
		safety: 8,
		reliability: 6,
		acceleration: 11.3,
	},
	{
		id: 6,
		brand: 'Citroen',
		model: 'C4 III (1.2 PureTech 130 EAT8)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 130,
		capacity: 1.2,
		yearFrom: 2021,
		yearTo: 2022,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 380,
		consumption: 5.8,
		maintenanceCost: 5,
		comfort: 8,
		price: 68000,
		safety: 8,
		reliability: 6,
		acceleration: 9.4,
	},
	{
		id: 7,
		brand: 'Citroen',
		model: 'C4 III (1.5 BlueHDi Diesel)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Diesel',
		power: 130,
		capacity: 1.5,
		yearFrom: 2021,
		yearTo: 2022,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 380,
		consumption: 4.6,
		maintenanceCost: 6,
		comfort: 8,
		price: 74000,
		safety: 8,
		reliability: 7,
		acceleration: 9.5,
	},

	// 3. SKODA SUPERB III (2017-2020)
	{
		id: 9,
		brand: 'Skoda',
		model: 'Superb III (1.5 TSI Manual)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Benzyna',
		power: 150,
		capacity: 1.5,
		yearFrom: 2017,
		yearTo: 2020,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 660,
		consumption: 6.1,
		maintenanceCost: 5,
		comfort: 8,
		price: 76000,
		safety: 10,
		reliability: 8,
		acceleration: 8.9,
	},
	{
		id: 10,
		brand: 'Skoda',
		model: 'Superb III (2.0 TSI DSG)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Benzyna',
		power: 220,
		capacity: 2.0,
		yearFrom: 2017,
		yearTo: 2020,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 660,
		consumption: 7.3,
		maintenanceCost: 6,
		comfort: 8,
		price: 88000,
		safety: 10,
		reliability: 7,
		acceleration: 7.0,
	},
	{
		id: 11,
		brand: 'Skoda',
		model: 'Superb III (2.0 TSI 4x4)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Benzyna',
		power: 280,
		capacity: 2.0,
		yearFrom: 2017,
		yearTo: 2020,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 660,
		consumption: 8.4,
		maintenanceCost: 7,
		comfort: 8,
		price: 112000,
		safety: 10,
		reliability: 7,
		acceleration: 5.8,
	},
	{
		id: 12,
		brand: 'Skoda',
		model: 'Superb III (2.0 TDI Manual)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Diesel',
		power: 150,
		capacity: 2.0,
		yearFrom: 2017,
		yearTo: 2020,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 660,
		consumption: 4.7,
		maintenanceCost: 5,
		comfort: 8,
		price: 69000,
		safety: 10,
		reliability: 8,
		acceleration: 9.1,
	},
	{
		id: 13,
		brand: 'Skoda',
		model: 'Superb III (2.0 TDI DSG)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Diesel',
		power: 190,
		capacity: 2.0,
		yearFrom: 2017,
		yearTo: 2020,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 660,
		consumption: 5.2,
		maintenanceCost: 6,
		comfort: 8,
		price: 98000,
		safety: 10,
		reliability: 7,
		acceleration: 8.0,
	},
	{
		id: 14,
		brand: 'Skoda',
		model: 'Superb III (2.0 TDI 4x4 DSG)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Diesel',
		power: 190,
		capacity: 2.0,
		yearFrom: 2017,
		yearTo: 2020,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 660,
		consumption: 5.7,
		maintenanceCost: 7,
		comfort: 8,
		price: 105000,
		safety: 10,
		reliability: 7,
		acceleration: 7.9,
	},
	{
		id: 15,
		brand: 'Skoda',
		model: 'Superb III iV (Plug-in)',
		condition: 'Używany',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Hybryda',
		power: 218,
		capacity: 1.4,
		yearFrom: 2017,
		yearTo: 2020,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 510,
		consumption: 3.5,
		maintenanceCost: 7,
		comfort: 9,
		price: 118000,
		safety: 10,
		reliability: 7,
		acceleration: 7.7,
	},

	// 4. AUDI Q7 4M (2017-2021)
	{
		id: 16,
		brand: 'Audi',
		model: 'Q7 45 TDI (231 KM)',
		condition: 'Używany',
		bodyType: 'SUV',
		seats: 7,
		fuel: 'Diesel',
		power: 231,
		capacity: 3.0,
		yearFrom: 2017,
		yearTo: 2021,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 890,
		consumption: 7.4,
		maintenanceCost: 8,
		comfort: 10,
		price: 185000,
		safety: 10,
		reliability: 7,
		acceleration: 7.1,
	},
	{
		id: 17,
		brand: 'Audi',
		model: 'Q7 50 TDI (286 KM)',
		condition: 'Używany',
		bodyType: 'SUV',
		seats: 7,
		fuel: 'Diesel',
		power: 286,
		capacity: 3.0,
		yearFrom: 2017,
		yearTo: 2021,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 890,
		consumption: 7.8,
		maintenanceCost: 9,
		comfort: 10,
		price: 235000,
		safety: 10,
		reliability: 7,
		acceleration: 6.1,
	},
	{
		id: 18,
		brand: 'Audi',
		model: 'Q7 55 TFSI (340 KM)',
		condition: 'Używany',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Benzyna',
		power: 340,
		capacity: 3.0,
		yearFrom: 2017,
		yearTo: 2021,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 890,
		consumption: 9.8,
		maintenanceCost: 9,
		comfort: 10,
		price: 249000,
		safety: 10,
		reliability: 7,
		acceleration: 5.9,
	},
	{
		id: 19,
		brand: 'Audi',
		model: 'SQ7 TDI (V8 435 KM)',
		condition: 'Używany',
		bodyType: 'SUV',
		seats: 7,
		fuel: 'Diesel',
		power: 435,
		capacity: 4.0,
		yearFrom: 2017,
		yearTo: 2021,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 890,
		consumption: 9.2,
		maintenanceCost: 10,
		comfort: 10,
		price: 260000,
		safety: 10,
		reliability: 6,
		acceleration: 4.8,
	},

	// 5. HONDA CIVIC IX (2014-2016)
	{
		id: 20,
		brand: 'Honda',
		model: 'Civic IX (1.4 i-VTEC)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 100,
		capacity: 1.4,
		yearFrom: 2014,
		yearTo: 2016,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 477,
		consumption: 5.5,
		maintenanceCost: 3,
		comfort: 6,
		price: 41000,
		safety: 9,
		reliability: 9,
		acceleration: 13.4,
	},
	{
		id: 21,
		brand: 'Honda',
		model: 'Civic IX (1.8 i-VTEC Manual)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 142,
		capacity: 1.8,
		yearFrom: 2014,
		yearTo: 2016,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 477,
		consumption: 6.8,
		maintenanceCost: 4,
		comfort: 6,
		price: 52000,
		safety: 10,
		reliability: 9,
		acceleration: 9.1,
	},
	{
		id: 22,
		brand: 'Honda',
		model: 'Civic IX (1.8 i-VTEC Automat)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 142,
		capacity: 1.8,
		yearFrom: 2014,
		yearTo: 2016,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 477,
		consumption: 7.3,
		maintenanceCost: 4,
		comfort: 6,
		price: 55000,
		safety: 10,
		reliability: 9,
		acceleration: 10.9,
	},
	{
		id: 23,
		brand: 'Honda',
		model: 'Civic IX (1.6 i-DTEC Diesel)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Diesel',
		power: 120,
		capacity: 1.6,
		yearFrom: 2014,
		yearTo: 2016,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 477,
		consumption: 4.1,
		maintenanceCost: 5,
		comfort: 6,
		price: 48000,
		safety: 10,
		reliability: 9,
		acceleration: 10.5,
	},
	{
		id: 24,
		brand: 'Honda',
		model: 'Civic IX Type R',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 4,
		fuel: 'Benzyna',
		power: 310,
		capacity: 2.0,
		yearFrom: 2014,
		yearTo: 2016,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 477,
		consumption: 8.6,
		maintenanceCost: 7,
		comfort: 4,
		price: 105000,
		safety: 9,
		reliability: 8,
		acceleration: 5.7,
	},

	// 6. FORD MUSTANG VI (2019-2020)
	{
		id: 25,
		brand: 'Ford',
		model: 'Mustang VI (2.3 EcoBoost Manual)',
		condition: 'Używany',
		bodyType: 'Coupe',
		seats: 4,
		fuel: 'Benzyna',
		power: 290,
		capacity: 2.3,
		yearFrom: 2019,
		yearTo: 2020,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 408,
		consumption: 9.1,
		maintenanceCost: 6,
		comfort: 6,
		price: 125000,
		safety: 6,
		reliability: 7,
		acceleration: 5.8,
	},
	{
		id: 26,
		brand: 'Ford',
		model: 'Mustang VI (2.3 EcoBoost A10)',
		condition: 'Używany',
		bodyType: 'Coupe',
		seats: 4,
		fuel: 'Benzyna',
		power: 290,
		capacity: 2.3,
		yearFrom: 2019,
		yearTo: 2020,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 408,
		consumption: 9.3,
		maintenanceCost: 6,
		comfort: 6,
		price: 132000,
		safety: 6,
		reliability: 7,
		acceleration: 5.5,
	},
	{
		id: 27,
		brand: 'Ford',
		model: 'Mustang VI (5.0 V8 GT Manual)',
		condition: 'Używany',
		bodyType: 'Coupe',
		seats: 4,
		fuel: 'Benzyna',
		power: 450,
		capacity: 5.0,
		yearFrom: 2019,
		yearTo: 2020,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 408,
		consumption: 12.5,
		maintenanceCost: 7,
		comfort: 6,
		price: 175000,
		safety: 6,
		reliability: 7,
		acceleration: 4.6,
	},
	{
		id: 28,
		brand: 'Ford',
		model: 'Mustang VI (5.0 V8 GT A10)',
		condition: 'Używany',
		bodyType: 'Coupe',
		seats: 4,
		fuel: 'Benzyna',
		power: 450,
		capacity: 5.0,
		yearFrom: 2019,
		yearTo: 2020,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 408,
		consumption: 12.1,
		maintenanceCost: 8,
		comfort: 6,
		price: 185000,
		safety: 6,
		reliability: 7,
		acceleration: 4.3,
	},

	// 7. TOYOTA YARIS III (2016-2018)
	{
		id: 29,
		brand: 'Toyota',
		model: 'Yaris III (1.0 VVT-i)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 69,
		capacity: 1.0,
		yearFrom: 2016,
		yearTo: 2018,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 286,
		consumption: 4.7,
		maintenanceCost: 2,
		comfort: 5,
		price: 38000,
		safety: 10,
		reliability: 9,
		acceleration: 15.3,
	},
	{
		id: 30,
		brand: 'Toyota',
		model: 'Yaris III (1.5 VVT-i Manual)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 111,
		capacity: 1.5,
		yearFrom: 2016,
		yearTo: 2018,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 286,
		consumption: 5.0,
		maintenanceCost: 3,
		comfort: 5,
		price: 46000,
		safety: 10,
		reliability: 9,
		acceleration: 11.0,
	},
	{
		id: 31,
		brand: 'Toyota',
		model: 'Yaris III (1.5 VVT-i CVT)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 111,
		capacity: 1.5,
		yearFrom: 2016,
		yearTo: 2018,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 286,
		consumption: 5.4,
		maintenanceCost: 3,
		comfort: 5,
		price: 49000,
		safety: 10,
		reliability: 9,
		acceleration: 11.2,
	},
	{
		id: 32,
		brand: 'Toyota',
		model: 'Yaris III (1.5 Hybrid)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Hybryda',
		power: 100,
		capacity: 1.5,
		yearFrom: 2016,
		yearTo: 2018,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 286,
		consumption: 3.8,
		maintenanceCost: 3,
		comfort: 5,
		price: 59000,
		safety: 10,
		reliability: 10,
		acceleration: 11.8,
	},
	{
		id: 33,
		brand: 'Toyota',
		model: 'Yaris III (1.4 D-4D)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Diesel',
		power: 90,
		capacity: 1.4,
		yearFrom: 2016,
		yearTo: 2018,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 286,
		consumption: 3.9,
		maintenanceCost: 4,
		comfort: 5,
		price: 41000,
		safety: 10,
		reliability: 8,
		acceleration: 10.8,
	},

	// 8. BMW SERIA 3 E90 (2009-2011)
	{
		id: 34,
		brand: 'BMW',
		model: 'Seria 3 E90 (318i)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 143,
		capacity: 2.0,
		yearFrom: 2009,
		yearTo: 2011,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 460,
		consumption: 6.5,
		maintenanceCost: 6,
		comfort: 7,
		price: 21000,
		safety: 8,
		reliability: 5,
		acceleration: 9.1,
	},
	{
		id: 35,
		brand: 'BMW',
		model: 'Seria 3 E90 (320i Automat)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 170,
		capacity: 2.0,
		yearFrom: 2009,
		yearTo: 2011,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 460,
		consumption: 7.2,
		maintenanceCost: 6,
		comfort: 7,
		price: 25000,
		safety: 8,
		reliability: 5,
		acceleration: 8.9,
	},
	{
		id: 36,
		brand: 'BMW',
		model: 'Seria 3 E90 (320d Manual)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Diesel',
		power: 177,
		capacity: 2.0,
		yearFrom: 2009,
		yearTo: 2011,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 460,
		consumption: 4.8,
		maintenanceCost: 7,
		comfort: 7,
		price: 22000,
		safety: 8,
		reliability: 4,
		acceleration: 7.9,
	},
	{
		id: 37,
		brand: 'BMW',
		model: 'Seria 3 E90 (320d Automat)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Diesel',
		power: 177,
		capacity: 2.0,
		yearFrom: 2009,
		yearTo: 2011,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 460,
		consumption: 5.4,
		maintenanceCost: 8,
		comfort: 7,
		price: 26000,
		safety: 8,
		reliability: 4,
		acceleration: 8.0,
	},
	{
		id: 38,
		brand: 'BMW',
		model: 'Seria 3 E90 (330d V6 Automat)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Diesel',
		power: 245,
		capacity: 3.0,
		yearFrom: 2009,
		yearTo: 2011,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 460,
		consumption: 6.2,
		maintenanceCost: 8,
		comfort: 8,
		price: 34000,
		safety: 8,
		reliability: 7,
		acceleration: 6.1,
	},
	{
		id: 39,
		brand: 'BMW',
		model: 'Seria 3 E90 (335i R6 Turbo)',
		condition: 'Używany',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 306,
		capacity: 3.0,
		yearFrom: 2009,
		yearTo: 2011,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 460,
		consumption: 9.1,
		maintenanceCost: 9,
		comfort: 8,
		price: 44000,
		safety: 8,
		reliability: 5,
		acceleration: 5.6,
	},

	// 9. VOLKSWAGEN GOLF VII (2015-2017)
	{
		id: 40,
		brand: 'Volkswagen',
		model: 'Golf VII (1.2 TSI Manual)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 110,
		capacity: 1.2,
		yearFrom: 2015,
		yearTo: 2017,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 380,
		consumption: 4.9,
		maintenanceCost: 4,
		comfort: 7,
		price: 44000,
		safety: 10,
		reliability: 7,
		acceleration: 9.9,
	},
	{
		id: 41,
		brand: 'Volkswagen',
		model: 'Golf VII (1.4 TSI DSG)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 150,
		capacity: 1.4,
		yearFrom: 2015,
		yearTo: 2017,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 380,
		consumption: 5.2,
		maintenanceCost: 5,
		comfort: 7,
		price: 54000,
		safety: 10,
		reliability: 8,
		acceleration: 8.2,
	},
	{
		id: 42,
		brand: 'Volkswagen',
		model: 'Golf VII (1.6 TDI Manual)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Diesel',
		power: 110,
		capacity: 1.6,
		yearFrom: 2015,
		yearTo: 2017,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 380,
		consumption: 3.9,
		maintenanceCost: 5,
		comfort: 7,
		price: 49000,
		safety: 10,
		reliability: 8,
		acceleration: 10.5,
	},
	{
		id: 43,
		brand: 'Volkswagen',
		model: 'Golf VII (2.0 TDI Manual)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Diesel',
		power: 150,
		capacity: 2.0,
		yearFrom: 2015,
		yearTo: 2017,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 380,
		consumption: 4.4,
		maintenanceCost: 5,
		comfort: 7,
		price: 55000,
		safety: 10,
		reliability: 8,
		acceleration: 8.6,
	},
	{
		id: 44,
		brand: 'Volkswagen',
		model: 'Golf VII (2.0 TDI DSG)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Diesel',
		power: 150,
		capacity: 2.0,
		yearFrom: 2015,
		yearTo: 2017,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 380,
		consumption: 5.0,
		maintenanceCost: 6,
		comfort: 7,
		price: 58000,
		safety: 10,
		reliability: 8,
		acceleration: 8.6,
	},
	{
		id: 45,
		brand: 'Volkswagen',
		model: 'Golf VII GTD (2.0 TDI 184 KM)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Diesel',
		power: 184,
		capacity: 2.0,
		yearFrom: 2015,
		yearTo: 2017,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 380,
		consumption: 4.9,
		maintenanceCost: 6,
		comfort: 7,
		price: 69000,
		safety: 10,
		reliability: 8,
		acceleration: 7.5,
	},
	{
		id: 46,
		brand: 'Volkswagen',
		model: 'Golf VII GTI (2.0 TSI 230 KM)',
		condition: 'Używany',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 230,
		capacity: 2.0,
		yearFrom: 2015,
		yearTo: 2017,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 380,
		consumption: 6.4,
		maintenanceCost: 7,
		comfort: 7,
		price: 79000,
		safety: 10,
		reliability: 7,
		acceleration: 6.4,
	},

	// 10. MAZDA MX-5 ND (2016-2019)
	{
		id: 47,
		brand: 'Mazda',
		model: 'MX-5 ND (1.5 SKYACTIV-G)',
		condition: 'Używany',
		bodyType: 'Coupe',
		seats: 2,
		fuel: 'Benzyna',
		power: 131,
		capacity: 1.5,
		yearFrom: 2016,
		yearTo: 2019,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 130,
		consumption: 6.1,
		maintenanceCost: 4,
		comfort: 4,
		price: 72000,
		safety: 8,
		reliability: 9,
		acceleration: 8.3,
	},
	{
		id: 48,
		brand: 'Mazda',
		model: 'MX-5 ND (2.0 SKYACTIV-G 160 KM)',
		condition: 'Używany',
		bodyType: 'Coupe',
		seats: 2,
		fuel: 'Benzyna',
		power: 160,
		capacity: 2.0,
		yearFrom: 2016,
		yearTo: 2019,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 130,
		consumption: 6.9,
		maintenanceCost: 5,
		comfort: 4,
		price: 88000,
		safety: 8,
		reliability: 9,
		acceleration: 7.3,
	},
	{
		id: 49,
		brand: 'Mazda',
		model: 'MX-5 ND (2.0 SKYACTIV-G 184 KM)',
		condition: 'Używany',
		bodyType: 'Coupe',
		seats: 2,
		fuel: 'Benzyna',
		power: 184,
		capacity: 2.0,
		yearFrom: 2016,
		yearTo: 2019,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 130,
		consumption: 6.9,
		maintenanceCost: 5,
		comfort: 4,
		price: 105000,
		safety: 8,
		reliability: 9,
		acceleration: 6.5,
	},

	// ==========================================
	// AUTA NOWE (Z salonu, 2024)
	// ==========================================

	// 11. TOYOTA COROLLA E21 (Nowe)
	{
		id: 50,
		brand: 'Toyota',
		model: 'Corolla (1.5 Dynamic Force Manual)',
		condition: 'Nowy',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 125,
		capacity: 1.5,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 471,
		consumption: 5.6,
		maintenanceCost: 3,
		comfort: 7,
		price: 106000,
		safety: 10,
		reliability: 10,
		acceleration: 10.2,
	},
	{
		id: 51,
		brand: 'Toyota',
		model: 'Corolla (1.8 Hybrid e-CVT)',
		condition: 'Nowy',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Hybryda',
		power: 140,
		capacity: 1.8,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 598,
		consumption: 4.6,
		maintenanceCost: 4,
		comfort: 7,
		price: 132000,
		safety: 10,
		reliability: 10,
		acceleration: 9.2,
	},
	{
		id: 52,
		brand: 'Toyota',
		model: 'Corolla (2.0 Hybrid 196 KM)',
		condition: 'Nowy',
		bodyType: 'Kombi',
		seats: 5,
		fuel: 'Hybryda',
		power: 196,
		capacity: 2.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 581,
		consumption: 4.7,
		maintenanceCost: 4,
		comfort: 8,
		price: 145000,
		safety: 10,
		reliability: 10,
		acceleration: 7.7,
	},

	// 12. BMW M3 G80 (Nowe)
	{
		id: 53,
		brand: 'BMW',
		model: 'M3 (480 KM Manual RWD)',
		condition: 'Nowy',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 480,
		capacity: 3.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 480,
		consumption: 10.8,
		maintenanceCost: 9,
		comfort: 7,
		price: 445000,
		safety: 10,
		reliability: 7,
		acceleration: 4.2,
	},
	{
		id: 54,
		brand: 'BMW',
		model: 'M3 Competition (510 KM RWD)',
		condition: 'Nowy',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 510,
		capacity: 3.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 480,
		consumption: 11.0,
		maintenanceCost: 10,
		comfort: 7,
		price: 475000,
		safety: 10,
		reliability: 7,
		acceleration: 3.9,
	},
	{
		id: 55,
		brand: 'BMW',
		model: 'M3 Competition xDrive (510 KM 4x4)',
		condition: 'Nowy',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Benzyna',
		power: 510,
		capacity: 3.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 480,
		consumption: 11.2,
		maintenanceCost: 10,
		comfort: 7,
		price: 495000,
		safety: 10,
		reliability: 7,
		acceleration: 3.5,
	},

	// 13. DACIA DUSTER III (Nowe)
	{
		id: 56,
		brand: 'Dacia',
		model: 'Duster III (1.0 ECO-G LPG)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'LPG',
		power: 100,
		capacity: 1.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 445,
		consumption: 7.8,
		maintenanceCost: 3,
		comfort: 5,
		price: 87000,
		safety: 6,
		reliability: 8,
		acceleration: 13.8,
	},
	{
		id: 57,
		brand: 'Dacia',
		model: 'Duster III (1.2 TCe 130 FWD)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Benzyna',
		power: 130,
		capacity: 1.2,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 472,
		consumption: 6.0,
		maintenanceCost: 4,
		comfort: 6,
		price: 96000,
		safety: 6,
		reliability: 8,
		acceleration: 9.9,
	},
	{
		id: 58,
		brand: 'Dacia',
		model: 'Duster III (1.2 TCe 130 4x4)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Benzyna',
		power: 130,
		capacity: 1.2,
		yearFrom: 2024,
		yearTo: null,
		drive: 'AWD',
		transmission: 'Manualna',
		trunkSize: 430,
		consumption: 6.4,
		maintenanceCost: 5,
		comfort: 6,
		price: 112000,
		safety: 6,
		reliability: 8,
		acceleration: 11.0,
	},
	{
		id: 59,
		brand: 'Dacia',
		model: 'Duster III (HYBRID 140 Automat)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Hybryda',
		power: 140,
		capacity: 1.6,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 430,
		consumption: 5.0,
		maintenanceCost: 4,
		comfort: 6,
		price: 117000,
		safety: 6,
		reliability: 8,
		acceleration: 10.1,
	},

	// 14. TESLA MODEL 3 (Nowe)
	{
		id: 60,
		brand: 'Tesla',
		model: 'Model 3 (RWD)',
		condition: 'Nowy',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Elektryk',
		power: 283,
		capacity: 0.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 425,
		consumption: 0.0,
		maintenanceCost: 4,
		comfort: 8,
		price: 194990,
		safety: 10,
		reliability: 7,
		acceleration: 6.1,
	},
	{
		id: 61,
		brand: 'Tesla',
		model: 'Model 3 (Long Range AWD)',
		condition: 'Nowy',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Elektryk',
		power: 498,
		capacity: 0.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 425,
		consumption: 0.0,
		maintenanceCost: 4,
		comfort: 8,
		price: 224990,
		safety: 10,
		reliability: 7,
		acceleration: 4.4,
	},
	{
		id: 62,
		brand: 'Tesla',
		model: 'Model 3 (Performance 4x4)',
		condition: 'Nowy',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Elektryk',
		power: 510,
		capacity: 0.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 425,
		consumption: 0.0,
		maintenanceCost: 5,
		comfort: 8,
		price: 244990,
		safety: 10,
		reliability: 7,
		acceleration: 3.1,
	},

	// 15. VOLVO XC60 II (Nowe)
	{
		id: 63,
		brand: 'Volvo',
		model: 'XC60 (B4 Mild Hybrid Benzyna)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Benzyna',
		power: 197,
		capacity: 2.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 468,
		consumption: 7.6,
		maintenanceCost: 7,
		comfort: 9,
		price: 219000,
		safety: 10,
		reliability: 8,
		acceleration: 8.1,
	},
	{
		id: 64,
		brand: 'Volvo',
		model: 'XC60 (B4 Mild Hybrid Diesel AWD)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Diesel',
		power: 197,
		capacity: 2.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 468,
		consumption: 6.3,
		maintenanceCost: 8,
		comfort: 9,
		price: 235000,
		safety: 10,
		reliability: 8,
		acceleration: 8.3,
	},
	{
		id: 65,
		brand: 'Volvo',
		model: 'XC60 (B5 Mild Hybrid Benzyna AWD)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Benzyna',
		power: 250,
		capacity: 2.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 468,
		consumption: 8.0,
		maintenanceCost: 8,
		comfort: 9,
		price: 252000,
		safety: 10,
		reliability: 8,
		acceleration: 6.9,
	},
	{
		id: 66,
		brand: 'Volvo',
		model: 'XC60 (T6 Recharge Plug-in)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Hybryda',
		power: 350,
		capacity: 2.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 468,
		consumption: 3.2,
		maintenanceCost: 8,
		comfort: 10,
		price: 265000,
		safety: 10,
		reliability: 8,
		acceleration: 5.7,
	},

	// 16. PORSCHE 911 992 (Nowe)
	{
		id: 67,
		brand: 'Porsche',
		model: '911 Carrera (394 KM PDK)',
		condition: 'Nowy',
		bodyType: 'Coupe',
		seats: 4,
		fuel: 'Benzyna',
		power: 394,
		capacity: 3.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'RWD',
		transmission: 'Automatyczna',
		trunkSize: 132,
		consumption: 10.3,
		maintenanceCost: 10,
		comfort: 7,
		price: 652000,
		safety: 10,
		reliability: 9,
		acceleration: 4.1,
	},
	{
		id: 68,
		brand: 'Porsche',
		model: '911 Carrera T (Manual)',
		condition: 'Nowy',
		bodyType: 'Coupe',
		seats: 4,
		fuel: 'Benzyna',
		power: 385,
		capacity: 3.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'RWD',
		transmission: 'Manualna',
		trunkSize: 132,
		consumption: 10.5,
		maintenanceCost: 10,
		comfort: 6,
		price: 670000,
		safety: 10,
		reliability: 9,
		acceleration: 4.5,
	},
	{
		id: 69,
		brand: 'Porsche',
		model: '911 Carrera 4S (450 KM 4x4)',
		condition: 'Nowy',
		bodyType: 'Coupe',
		seats: 4,
		fuel: 'Benzyna',
		power: 450,
		capacity: 3.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 132,
		consumption: 11.1,
		maintenanceCost: 10,
		comfort: 7,
		price: 740000,
		safety: 10,
		reliability: 9,
		acceleration: 3.4,
	},

	// 17. HYUNDAI TUCSON IV (Nowe)
	{
		id: 70,
		brand: 'Hyundai',
		model: 'Tucson IV (1.6 T-GDI Manual)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Benzyna',
		power: 150,
		capacity: 1.6,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 620,
		consumption: 6.8,
		maintenanceCost: 4,
		comfort: 8,
		price: 125000,
		safety: 10,
		reliability: 9,
		acceleration: 10.3,
	},
	{
		id: 71,
		brand: 'Hyundai',
		model: 'Tucson IV (1.6 T-GDI 7DCT)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Benzyna',
		power: 150,
		capacity: 1.6,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 620,
		consumption: 7.0,
		maintenanceCost: 5,
		comfort: 8,
		price: 138000,
		safety: 10,
		reliability: 9,
		acceleration: 9.6,
	},
	{
		id: 72,
		brand: 'Hyundai',
		model: 'Tucson IV (1.6 HEV Hybryda 2WD)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Hybryda',
		power: 215,
		capacity: 1.6,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 616,
		consumption: 5.6,
		maintenanceCost: 5,
		comfort: 8,
		price: 159000,
		safety: 10,
		reliability: 9,
		acceleration: 8.2,
	},
	{
		id: 73,
		brand: 'Hyundai',
		model: 'Tucson IV (1.6 HEV Hybryda 4WD)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Hybryda',
		power: 215,
		capacity: 1.6,
		yearFrom: 2024,
		yearTo: null,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 616,
		consumption: 6.1,
		maintenanceCost: 6,
		comfort: 8,
		price: 169000,
		safety: 10,
		reliability: 9,
		acceleration: 8.0,
	},
	{
		id: 74,
		brand: 'Hyundai',
		model: 'Tucson IV (1.6 PHEV 265 KM 4x4)',
		condition: 'Nowy',
		bodyType: 'SUV',
		seats: 5,
		fuel: 'Hybryda',
		power: 265,
		capacity: 1.6,
		yearFrom: 2024,
		yearTo: null,
		drive: 'AWD',
		transmission: 'Automatyczna',
		trunkSize: 558,
		consumption: 3.0,
		maintenanceCost: 6,
		comfort: 8,
		price: 195000,
		safety: 10,
		reliability: 9,
		acceleration: 7.9,
	},

	// 18. KIA CEED III (Nowe)
	{
		id: 75,
		brand: 'Kia',
		model: 'Ceed III (1.0 T-GDI Manual)',
		condition: 'Nowy',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 100,
		capacity: 1.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 395,
		consumption: 5.4,
		maintenanceCost: 4,
		comfort: 6,
		price: 92000,
		safety: 8,
		reliability: 9,
		acceleration: 11.8,
	},
	{
		id: 76,
		brand: 'Kia',
		model: 'Ceed III (1.5 T-GDI Manual)',
		condition: 'Nowy',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 160,
		capacity: 1.5,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 395,
		consumption: 5.8,
		maintenanceCost: 5,
		comfort: 7,
		price: 108000,
		safety: 8,
		reliability: 9,
		acceleration: 8.4,
	},
	{
		id: 77,
		brand: 'Kia',
		model: 'Ceed III (1.5 T-GDI 7DCT)',
		condition: 'Nowy',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 160,
		capacity: 1.5,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 395,
		consumption: 6.0,
		maintenanceCost: 5,
		comfort: 7,
		price: 116000,
		safety: 8,
		reliability: 9,
		acceleration: 8.6,
	},
	{
		id: 78,
		brand: 'Kia',
		model: 'Ceed III (1.6 CRDi Diesel DCT)',
		condition: 'Nowy',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Diesel',
		power: 136,
		capacity: 1.6,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 395,
		consumption: 4.4,
		maintenanceCost: 6,
		comfort: 7,
		price: 122000,
		safety: 8,
		reliability: 8,
		acceleration: 9.9,
	},

	// 19. LEXUS ES VII (Nowe)
	{
		id: 79,
		brand: 'Lexus',
		model: 'ES 300h (2.5 Hybryda)',
		condition: 'Nowy',
		bodyType: 'Sedan',
		seats: 5,
		fuel: 'Hybryda',
		power: 218,
		capacity: 2.5,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 454,
		consumption: 4.8,
		maintenanceCost: 6,
		comfort: 10,
		price: 245000,
		safety: 10,
		reliability: 10,
		acceleration: 8.9,
	},

	// 20. RENAULT CLIO V (Nowe)
	{
		id: 80,
		brand: 'Renault',
		model: 'Clio V (1.0 TCe 90 KM)',
		condition: 'Nowy',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Benzyna',
		power: 90,
		capacity: 1.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 391,
		consumption: 5.2,
		maintenanceCost: 4,
		comfort: 6,
		price: 74000,
		safety: 10,
		reliability: 8,
		acceleration: 12.2,
	},
	{
		id: 81,
		brand: 'Renault',
		model: 'Clio V (1.0 TCe LPG 100 KM)',
		condition: 'Nowy',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'LPG',
		power: 100,
		capacity: 1.0,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Manualna',
		trunkSize: 391,
		consumption: 7.2,
		maintenanceCost: 4,
		comfort: 6,
		price: 81000,
		safety: 10,
		reliability: 8,
		acceleration: 11.8,
	},
	{
		id: 82,
		brand: 'Renault',
		model: 'Clio V (1.6 E-Tech Hybryda)',
		condition: 'Nowy',
		bodyType: 'Hatchback',
		seats: 5,
		fuel: 'Hybryda',
		power: 145,
		capacity: 1.6,
		yearFrom: 2024,
		yearTo: null,
		drive: 'FWD',
		transmission: 'Automatyczna',
		trunkSize: 301,
		consumption: 4.2,
		maintenanceCost: 5,
		comfort: 7,
		price: 99000,
		safety: 10,
		reliability: 8,
		acceleration: 9.3,
	},
]
